### ISSUE TITLE
hover effect on sponsor cards in competitions

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/website-experimental#100]
The hover effect doesn't work on the sponsor cards. This is as intended?

The culprit is because the benchmark cards are a link while the sponsor cards the link is in the cards
```css
a .card-shadow:hover {
  box-shadow: 0 8px 16px rgba(0,0,0,.4);
}
```
