### ISSUE TITLE
remove custom navbar transition with quarto 1.3

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/website-experimental#109]
when quarto release 1.3 remove below code from styles.css. And test if it works

```css
header#quarto-header {
    transition: all 200ms linear;
}
```
