### ISSUE TITLE
Wes Lewis missing from team page under task leaders

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website-experimental#57]
Task leader for denoising

**Comment by KaiWaldrant** [comment]
@WesLewis please provide a picture and organization details see example below:
```yaml
organizations:
  - name: Northwestern University
    href: 'https://www.northwestern.edu/'
    role: PhD student
```
