### ISSUE TITLE
remove unused in styles.css

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/website-experimental#98]
The `info-text` class is not used in our files so I would just remove this ?
```css
.card-shadow .info-text {
  padding: 0.5rem 0;
}

.card-shadow:hover .info-text,
.card-shadow:focus .info-text {
  color: #ff414b;
}
```

**Comment by KaiWaldrant** [comment]
I would also leave this with the `card` class as the button has nothing to do with the `card-shadow` class.

```css
.card-shadow .btn {
  margin-top: 0.5rem;
  padding: .2rem;
}
```
suggestion
```css
.card .btn {
  margin-top: 0.5rem;
  padding: .2rem;
}
```
